### ISSUE TITLE
레이스 페이지 쪽 슬라이더

### ISSUE THREAD

**Issue by amykim928** [KKooWoon/Front#15]
제가 레이스 페이지 쪽 슬라이더를 만들어보긴 했는데
1. 슬라이더를 한 줄에 두 개씩 보여지게 하는 것
2. 진행 중인 레이스 목록에서 슬라이더 뒤에 생성하기 버튼을 붙이는 것
이 두 가지 이슈가 잘 해결이 안 되네요.. 혹시 어떤 식으로 구현하면 될까요?

**Comment by homiekim** [comment]
1. 레이스 페이지의 내 레이스 tab을 말하시는 것 맞나요?
레이스 리스트가 슬라이드 형식으로 개발해야 하는 건 디자이너 분의 요구사항인가요?
제가 보기엔 페이지 양옆에 padding이 있는 걸로 보아 그냥 grid 형식으로 생각됩니다

2. 슬라이더 뒤에 버튼을 넣으려면
` ``<ImageSlider SliderHeight={height}>
          {data.map((v, i) => (
            <div key={i} onClick={() => setNow && setNow(v.raceId)}>
              <RaceItem item={v} isActive={now === v.raceId} styleType={styleType} />
            </div>
          ))}
         /* 요기에 버튼을 넣어야 하겠네요*/
        </ImageSlider>```
