### ISSUE TITLE
운동등록 페이지 이미지 슬라이더

### ISSUE THREAD

**Issue by homiekim** [KKooWoon/Front#6]
텍스트가 안움직이는 이유는 position : absolute 라서 그렇습니다.
position absolute로 지정 시 본래 자기 위치에서 고정 되는데 자기 위치가 어떻게 결정 되냐면 상위 태그 중 position: relative 를 기준으로 합니다. register-race.style.ts에 ItemWrapper 에서 position을 relative로 지정해보세요

이미지 슬라이더가 정확히 동작해도 왜 register 페이지의 width가 407로 고정되는 문제가 있는 것 같습니다. (이미지 슬라이더의 width는 screen width-20로 정상동작합니다.)

margin을 0으로 지정해도 새로 고침시 마진이 생겨버리는 문제는 정확히 어디 부분인지를 몰라서 살펴보기 어렵습니다. 말씀만 들었을 때 새로 고침 되면서 컴포넌트가 마운트 될 때 스타일이 지정되어있을 수 도 있을 것 같습니다. 예를 들면
`<div style={{ margin : "20px"}}>example</div>`
이런 식으로요, 한번 살펴 보시고 그래도 해결이 안되면 정확히 어느 부분에 마진이 0이 되어야 하는지 말씀주세요

**Comment by amykim928** [comment]
네 레이스는 해결했습니다.
마진 값은 제가 좀 더 해보고 해결이 안 되면 다시 물어볼게요 감사합니다:)
